service: route53-backup-lambda # NOTE: update this with your service name
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "route53:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource:
        - "*"

  # you can define service wide environment variables here
  environment:
    # Name of the S3 bucket to upload the backups to
    DESTINATION_S3_BUCKET_NAME: bob2build-backup
    # From/To address of notification email. It must be registered and verified at AWS SES console.
    NOTIFICATION_EMAIL_SENDER: bob2build.2020@gmail.com
    NOTIFICATION_EMAIL_RECEIVER: printfbabu@gmail.com
    # Either the ID or HOSTEDZONE_NAME can be specified.
    HOSTEDZONE_ID: ZC4CZWMIWATX

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  backup:
    handler: bin/operator
    events:
      - schedule: rate(2 hours)
